version: '2'

services:
  app:
    build: "./"
    ports:
      - "3001:3001"
    volumes:
      - "./:/opt/app"
    env_file: .env

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
    environment:
      CONN_NAME: default
      DB_HOST: localhost
      DB_NAME: database

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
